name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest pytest-cov pip-audit

      - name: Run tests
        run: pytest app/test.py --cov=app/

      - name: Dependency Audit
        run: pip-audit

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install linters
        run: |
          python -m pip install flake8 black

      - name: Run flake8
        run: flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run black
        run: black --check app/

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t spam-detection .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv trivy /usr/local/bin/

      - name: Check Dockerfile vulnerabilities with Trivy
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Check Docker image vulnerabilities with Trivy
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL spam-detection
